// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var MaterialUi_Icons = require("@jsiebern/bs-material-ui/src/MaterialUi_Icons.bs.js");
var MaterialUi_Paper = require("@jsiebern/bs-material-ui/src/MaterialUi_Paper.bs.js");
var MaterialUi_Table = require("@jsiebern/bs-material-ui/src/MaterialUi_Table.bs.js");
var MaterialUi_TableBody = require("@jsiebern/bs-material-ui/src/MaterialUi_TableBody.bs.js");
var MaterialUi_TableHead = require("@jsiebern/bs-material-ui/src/MaterialUi_TableHead.bs.js");
var MaterialUi_TextField = require("@jsiebern/bs-material-ui/src/MaterialUi_TextField.bs.js");
var MaterialUi_Typography = require("@jsiebern/bs-material-ui/src/MaterialUi_Typography.bs.js");
var MaterialUi_CssBaseline = require("@jsiebern/bs-material-ui/src/MaterialUi_CssBaseline.bs.js");

var traits = /* array */[
  "Music Taste",
  "Met at college",
  "Met at work"
];

function parseGuestText(s) {
  return $$Array.map((function (p) {
                return p.split((/, ?/));
              }), s.split("\n"));
}

var component = ReasonReact.reducerComponent("Example");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var orDash = function (g, i) {
                return Belt_Option.getWithDefault(Belt_Array.get(g, i), "-");
              };
              var boolOrDash = function (g, i) {
                return Belt_Option.getWithDefault(Belt_Option.map(Belt_Array.get(g, i), (function (param) {
                                  var exit = 0;
                                  switch (param) {
                                    case "false" : 
                                    case "n" : 
                                    case "no" : 
                                        exit = 2;
                                        break;
                                    case "true" : 
                                    case "y" : 
                                    case "yes" : 
                                        exit = 1;
                                        break;
                                    default:
                                      return ReasonReact.element(undefined, undefined, MaterialUi_Icons.make(/* ErrorOutline */-620738374, undefined, undefined, undefined, /* Small */311976103, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[]));
                                  }
                                  switch (exit) {
                                    case 1 : 
                                        return ReasonReact.element(undefined, undefined, MaterialUi_Icons.make(/* Check */-656144216, undefined, undefined, undefined, /* Small */311976103, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[]));
                                    case 2 : 
                                        return ReasonReact.element(undefined, undefined, MaterialUi_Icons.make(/* Close */-611285096, undefined, undefined, undefined, /* Small */311976103, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[]));
                                    
                                  }
                                })), React.createElement("div", undefined, "-"));
              };
              return React.createElement("main", {
                          className: Css.style(/* :: */[
                                Css.width(Css.px(960)),
                                /* :: */[
                                  Css.marginLeft(Css.auto),
                                  /* :: */[
                                    Css.marginRight(Css.auto),
                                    /* :: */[
                                      Css.padding(Css.px(20)),
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ])
                        }, ReasonReact.element(undefined, undefined, MaterialUi_CssBaseline.make(/* array */[])), ReasonReact.element(undefined, undefined, MaterialUi_Paper.make(Css.style(/* :: */[
                                      Css.padding(Css.px(20)),
                                      /* [] */0
                                    ]), undefined, undefined, undefined, undefined, undefined, /* array */[
                                  ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* H2 */16106, undefined, undefined, /* array */["Seating planner"])),
                                  ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* H4 */16108, undefined, undefined, /* array */["Guests"])),
                                  ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, Css.style(/* :: */[
                                                Css.paddingTop(Css.px(10)),
                                                /* [] */0
                                              ]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Enter your guests below, one per line. Seperate the traits by a comma, e.g:"])),
                                  ReasonReact.element(undefined, undefined, MaterialUi_Typography.make(undefined, Css.style(/* :: */[
                                                Css.paddingBottom(Css.px(10)),
                                                /* :: */[
                                                  Css.fontFamily("monospace"),
                                                  /* :: */[
                                                    Css.whiteSpace(/* pre */5595171),
                                                    /* [] */0
                                                  ]
                                                ]
                                              ]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */["Matt, Drum and Bass, y, y"])),
                                  ReasonReact.element(undefined, undefined, MaterialUi_TextField.make(undefined, undefined, Css.style(/* :: */[
                                                Css.fontFamily("monospace"),
                                                /* :: */[
                                                  Css.whiteSpace(/* pre */5595171),
                                                  /* :: */[
                                                    Css.width(Css.pct(80)),
                                                    /* :: */[
                                                      Css.paddingBottom(Css.px(20)),
                                                      /* [] */0
                                                    ]
                                                  ]
                                                ]
                                              ]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, (function (e) {
                                              return Curry._1(self[/* send */3], /* GuestTextChanged */[e.target.value]);
                                            }), undefined, "Enter guest details", undefined, /* `Int */[
                                            3654863,
                                            5
                                          ], /* `Int */[
                                            3654863,
                                            10
                                          ], undefined, undefined, undefined, undefined, undefined, undefined, /* array */[])),
                                  ReasonReact.element(undefined, undefined, MaterialUi_Table.make(undefined, undefined, undefined, undefined, undefined, /* array */[
                                            ReasonReact.element(undefined, undefined, MaterialUi_TableHead.make(undefined, undefined, undefined, undefined, /* array */[React.createElement("tr", undefined, React.createElement("td", undefined, "Name"), $$Array.map((function (t) {
                                                                  return React.createElement("td", undefined, t);
                                                                }), traits))])),
                                            ReasonReact.element(undefined, undefined, MaterialUi_TableBody.make(undefined, undefined, undefined, undefined, /* array */[$$Array.map((function (g) {
                                                              return React.createElement("tr", undefined, React.createElement("td", undefined, orDash(g, 0)), React.createElement("td", undefined, orDash(g, 1)), React.createElement("td", undefined, boolOrDash(g, 2)), React.createElement("td", undefined, boolOrDash(g, 3)));
                                                            }), self[/* state */1][/* guests */0])]))
                                          ]))
                                ])));
            }),
          /* initialState */(function (param) {
              return /* record */[/* guests : array */[]];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              return /* Update */Block.__(0, [/* record */[/* guests */parseGuestText(action[0])]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.traits = traits;
exports.parseGuestText = parseGuestText;
exports.component = component;
exports.make = make;
/* component Not a pure module */
